import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import LanguageDetector from 'i18next-browser-languagedetector';

i18n
  // detect user language
  // learn more: https://github.com/i18next/i18next-browser-languageDetector
  .use(LanguageDetector)
  // pass the i18n instance to react-i18next.
  .use(initReactI18next)
  // init i18next
  // for all options read: https://www.i18next.com/overview/configuration-options
  .init({
    debug: true,
    lng: "ko",
    fallbackLng: 'en',
    interpolation: {
      escapeValue: false, // not needed for react as it escapes by default
    },
    resources: {
      ko: {
        translation: {
          menu: {
            nav1: "가격정책",
            language : "KOR",
            nav2: "로그인",
            btn: "무료로 시작하기",
            text: "VRIN 3D를 사용해보고 싶다면"
          },
          main: {
            section01: {
              text1: "AI로 만드는 3D 모델",
              text2: "인공지능으로 자동 생성되는 3D 모델과",
              text3: "손쉬운 편집을 경험해보세요.",
              btn: "무료로 시작하기"
            },
            section02: {
              text1: "모바일 기반의",
              text2: "간편한 3D 스캐닝",
              text3: "스튜디오와 고가의 스캐너 없이도",
              text4: "누구나, 언제든",
            },
            section03: {
              text1: "AI 기술로 더욱 빠르고",
              text2: "더욱 리얼하게",
              text3: "3D 모델을 제작하세요.",
            },
            section04: {
              text1: "3D의 손쉬운 편집과",
              text2: "다양한 활용",
              text3: "VRIN 3D와 함께 시작하세요.",
            },
            section05: {
              caption: "The simplest way to generate",
              title: "시간도 비용도 절약하는 3D 모델 제작",
              description1: "무겁고 비싼 3D 스캐닝 장비없이 핸드폰 하나로 완성되는 3D,",
              description2: "시간과 비용을 절약해 콘텐츠를 효율적으로 제작하세요.",
              content1: "기기비용 절감",
              text1: "3D 스캐너 기준",
              content2: "시간 감축",
              text2: "모델러 작업시간 기준",
              content3: "에셋 생성비용 절감",
              text3: "모델러 인건비 기준",
            },
            section06: {
              caption: "One-stop solution",
              title: "스캔부터 편집까지 VRIN 3D에서 한번에",
              text1: "<div>모바일 기반의</div><div>간편한</div><div>3D 스캐닝</div>",
              text2: "<div>스튜디오와 고가의 스캐너 없이도</div><div>누구나, 언제나 가능한 3D 스캐닝</div>",
              text3: "<div>누구나 손쉬운 편집이</div><div>가능하도록</div><div>VRIN 3D</div><div>에디터</div>",
              text4: "<div>AI 재질 생성, 배경 편집 등</div><div>에셋을 빠르게 편집</div>",
            },
            section07: {
              caption: "Various contents with VRIN 3D",
              title: "생성한 3D 모델로 제작하는 다양한 콘텐츠",
              description1: "VRIN 3D에서 제작한 3D 모델을 다운받아\n상품 홍보, 가상쇼룸, 광고 VFX 등에 사용하세요",
              content1: "가상쇼룸",
              content2: "전시",
              content3: "상품홍보",
            }
          },
          modal: {
            text1: "3D 프린팅 이벤트",
            text2: "<div>나의 소중한 물건을</div><div>3D 피규어로 받아보세요</div>",
            text3: "기록하고 싶은 사물, 혹은 사람을 VRIN 3D로 촬영하고 피규어로 만들어보세요. 3D 프린팅하여 배송까지 해드립니다.",
            text4: "*이 이벤트는 한국, 일본 지역에서만 참여 가능합니다.",
            text5: "자세히 알아보기",
            text6: "오늘 하루 보지 않기",
            text7: "*한국, 일본 지역에서만 참여 가능합니다."
          },
          float: {
            text1 : "아직도 망설여지세요?",
            text2: "무료로 시작하기"
          }
        }
      },
      en: {
        translation: {
          menu: {
            nav1: "Pricing",
            language : "ENG",
            nav2: "Log in",
            btn: "Get started for free",
            text: "If you want to use VRIN 3D"
          },
          main: {
            section01: {
              text1: "3D Model generated with AI",
              text2: "Experience 3D model",
              text3: "automatically generated by AI and easy-to-use editing.",
              btn: "Get started for free"
            },
            section02: {
              text1: "Convenient 3D scanning",
              text2: "on Mobile Devices",
              text3: "Without any studio or fancy scanner",
              text4: "Anyone, Anywhere.",
            },
            section03: {
              text1: "Faster and more realistic",
              text2: "with our AI technology",
              text3: "Create 3D model now.",
            },
            section04: {
              text1: "Easy editing of 3D model",
              text2: "and versatile application",
              text3: "Start creating with VRIN 3D.",
            },
            section05: {
              caption: "The simplest way to generate",
              title: "3D model production the saves time and cost",
              description1: "Make 3D model using only smartphone without heavy, expensive 3D scanner",
              description2: "save time and cost to produce the contents more effectively.",
              content1: "Cost-saving\non equipment",
              text1: "Based on 3D Scanner",
              content2: "Time reduced",
              text2: "Based on modeler work",
              content3: "Cost-saving\non asset production",
              text3: "Based on modeler labor cost",
            },
            section06: {
              caption: "One-stop solution",
              title: "From scanning to editing\nat one go with VRIN 3D",
              text1: "<div>Mobile-based</div><div>Easy-to-use</div><div>3D scanning</div>",
              text2: "<div>3D scanning made possible</div><div>for anyone, anywhere</div><div>Without studio</div><div>and expensive scanner</div>",
              text3: "<div>VRIN 3D editor,</div><div>anyone can</div><div>edit easily</div>",
              text4: "<div>Quickly edit asset with</div><div>AI-generated material</div><div>background editing</div>",
            },
            section07: {
              caption: "Various contents with VRIN 3D",
              title: "Various contents\ncreated using 3D models",
              description1: "Download 3D model VRIN 3D prefabricated, use it for promotion, VR showroom, commercial VFX.",
              content1: "Virtual Showroom",
              content2: "Exhibition",
              content3: "Product Promotion",
            }
          },
          modal: {
            text1: "3D object print event",
            text2: "<div>Turn your treasures</div><div>into 3D figures</div>",
            text3: "Capture the objects or people you want to cherish with VRIN 3D and turn them into figures. Let us take care of the 3D printing and delivery for you.",
            text4: "*Only Korea and Japan area are available for this event.",
            text5: "Learn more",
            text6: "Don't show me today",
            text7: "Korea and Japan area are available for this event."
          },
          float: {
            text1 : "Still hesitating?",
            text2: "Get started for free"
          }
        }
      }
    }
  });

export default i18n;