import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import LanguageDetector from 'i18next-browser-languagedetector';

i18n
  // detect user language
  // learn more: https://github.com/i18next/i18next-browser-languageDetector
  .use(LanguageDetector)
  // pass the i18n instance to react-i18next.
  .use(initReactI18next)
  // init i18next
  // for all options read: https://www.i18next.com/overview/configuration-options
  .init({
    debug: true,
    lng: "ko",
    fallbackLng: 'en',
    interpolation: {
      escapeValue: false, // not needed for react as it escapes by default
    },
    resources: {
      ko: {
        translation: {
          menu: {
            language : "KOR"
          },
          main: {
            section01: {
              text1: "AI로 만드는 3D 모델",
              text2: "인공지능으로 자동 생성되는 3D 모델과",
              text3: "손쉬운 편집을 경험해보세요.",
              btn: "무료로 시작하기"
            },
            section02: {
              text1: "모바일 기반의",
              text2: "간편한 3D 스캐닝",
              text3: "스튜디오와 고가의 스캐너 없이도",
              text4: "누구나, 언제든",
            },
            section03: {
              text1: "AI 기술로 더욱 빠르고",
              text2: "더욱 리얼하게",
              text3: "3D 모델을 제작하세요.",
            },
            section04: {
              text1: "3D의 손쉬운 편집과",
              text2: "다양한 활용",
              text3: "VRIN 3D와 함께 시작하세요.",
            }
          }
        }
      },
      en: {
        translation: {
          menu: {
            language : "ENG"
          },
          main: {
            section1: {
              text1: "3D Model generated with AI",
              text2: "Experience 3D model",
              text3: "automatically generated by AI and easy-to-use editing.",
              btn: "Get started for free"
            },
            section2: {
              text1: "Convenient 3D scanning",
              text2: "on Mobile Devices",
              text3: "Without any studio or fancy scanner",
              text4: "Anyone, Anywhere.",
            },
            section03: {
              text1: "Faster and more realistic",
              text2: "with our AI technology",
              text3: "Create 3D model now.",
            },
            section04: {
              text1: "Easy editing of 3D model",
              text2: "and versatile application",
              text3: "Start creating with VRIN 3D.",
            }
          }
        }
      }
    }
  });

export default i18n;