import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import LanguageDetector from 'i18next-browser-languagedetector';

i18n
  // detect user language
  // learn more: https://github.com/i18next/i18next-browser-languageDetector
  .use(LanguageDetector)
  // pass the i18n instance to react-i18next.
  .use(initReactI18next)
  // init i18next
  // for all options read: https://www.i18next.com/overview/configuration-options
  .init({
    debug: true,
    lng: "ko",
    fallbackLng: 'en',
    interpolation: {
      escapeValue: false, // not needed for react as it escapes by default
    },
    resources: {
      ko: {
        translation: {
          menu: {
            language : "KOR"
          },
          main: {
            section01: {
              text1: "AI로 만드는 3D 모델",
              text2: "인공지능으로 자동 생성되는 3D 모델과 손쉬운 편집을 경험해보세요.",
              text3: "무료로 시작하기"
            }
          }
        }
      },
      en: {
        translation: {
          menu: {
            language : "ENG"
          },
          main: {
            section01: {
              text1: "3D Model generated with AI",
              text2: "Experience 3D model automatically generated by AI and easy-to-use editing.",
              text3: "Get started for free"
            }
          }
        }
      }
    }
  });

export default i18n;